import numpy as np
from itertools import groupby

#filename = "C:/Users/User/OneDrive - The University of Manchester/Year 3/Estado Sólido/sss/Solid-State-Project/Data/mean_sq_dev_vel_for_t_5e-1ps.txt"
filename = r'/Users/maxbehrens/OneDrive - UAM/Solid State/Solid-State-Project/Data/Confirm_Drude_temperature_distb/mean_sq_dev_vel_for_t_5e-1ps.txt'

def ReadData(filename, sim_type):
    """Reads data from txt file generated by sss

    Args:
        filename: path to data file

    Returns:
        data: time, x, y, E-field/E-excess (depending on model)
    """
    array_list = []
    with open(filename) as f_data:    
        for k, g in groupby(f_data, lambda x: x.startswith('&')):
            if not k:
                array_list.append(np.array([[float(x) for x in d.split()] for d in g if len(d.strip())]))
        array_list = np.array(array_list[:3])
    if sim_type == "sommer":
        return array_list[0,:,0], array_list[1,:,1], array_list[0,:,1], array_list[2,:,1]
    elif sim_type == "drude":
        return array_list[0,:,0], array_list[0,:,1], array_list[2,:,1], array_list[1,:,1]
    else:
        print('Please enter valid sim_type')
